### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by Mattue** [comment]
Can I ask how you found it and why you liked it?

**Comment by jpbida** [comment]
Thanks! I am just evaluating free games. Yours appeared in a search for "Math Game". I sent out pull requests to add a license to a subset that appeared to match the tech stacks I am interested.

**Comment by Mattue** [comment]
Well, it's not like "Math Game", it's like ["Heads Up!"](http://www.ellentv.com/page/2013/04/23/heads-up/), but with math words and all russian.

**Comment by Jack-Coder-007** [comment]
Hi, there, I have added the MIT License, you are good to go, just let you know, this game is just a demo version which I made in the University for a project, if you need to make it like a real game with several stages, you may add more features to it. Good Luck!

**Comment by jpbida** [comment]
Thanks!

**Comment by jpbida** [comment]
Interesting. I run and afterschool coding camp and want a bunch of starting
points for my students to play and modify. Not sure if your code will fit
into that category but if it does its good to know how you would want us to
use it.

**Pull request merged**
